// Generated by https://quicktype.io

export interface NewsResponse {
  msg:       string;
  ok: boolean;
  products:     Article[];
}

export interface Article {
  name:        string;
  description: string;
  image:          string;
  price: string;
}
